module.exports = {
  database: 'default',
  school: 'Placeholder SHS',
  title: 'Sport Selection',
  lightColor: '#0094ff',
  darkColor: '#0034ff',
  darkNavColor: '#f0f0ff',
  lightNavColor: '#f7f7ff',
  plusColor: '#1e3a63',
  hoverColor: '#00a4',
  activeColor: '#00a2',
  endPoint: 'https://sportselection-rest.ethanbulmer.com/sport-selection-username-and-password',
  adminEndPoint: 'https://sportselection-rest.ethanbulmer.com/sport-selection-admin-username-and-password',
  adminBulkEndPoint: 'https://sportselection-rest.ethanbulmer.com/sport-selection-admin-bulk-username-and-password',
};
